### ISSUE TITLE
Use path to support local schemas in addition to URLs

### ISSUE THREAD

**Issue by brianespinosa** [walbo/validate-json#152]
Hi @walbo 

Great action. I love how you've taken the time to put together some thoughtful tests for different schema drafts too.

I am hoping to use local schemas that are not published at a URL in order to validate JSON data. This does work within VSCode but I would love to add those checks into CI so people using different editors (or no editors at all) can validate their data.

## Example:

```
"$schema": "../schemas/teams.schema.json",
```
This schema references a sibling directory containing schemas that are part of my particular repository. I'd like those schemas to potentially change with the data they are validating within any given branch/PR. This is obviously not a URL, but a relative file path. I have not looked yet if this is something that is being limited by `ajv` or not. Basically, I think the action logic just needs to get updated to check if we are dealing with a URL for the schema, or a file path, in which case we could just use node `path` to resolve these schemas and pull things together.

Do you have any interest in accepting a PR that adds this functionality, with tests?

**Comment by walbo** [comment]
Hi @brianespinosa 

Contributions are welcome and the feature request seems reasonable to me :)
